site_name: Visera Engine
site_description: Visera Engine documentation.
site_url: https://visera.io/
repo_url: https://github.com/Visera-io/Visera-II
repo_name: Visera

theme:
  name: material
  language: en
  logo: assets/images/Visera.png
  favicon: assets/images/Visera.png
  palette:
    # Light mode
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - search.highlight
    - content.tabs.link

nav:
  - Home: index.md
  - Engine:
      - Core:
          - Overview: Engine/Core/index.md
          - Algorithm:
              - Overview: Engine/Core/Algorithm/index.md
              - Ranges: Engine/Core/Algorithm/Ranges.md
          - Compression: Engine/Core/Compression/index.md
          - Concurrency:
              - Overview: Engine/Core/Concurrency/index.md
              - Async: Engine/Core/Concurrency/Async.md
              - Channel:
                  - Overview: Engine/Core/Concurrency/Channel/index.md
                  - MPSC: Engine/Core/Concurrency/Channel/MPSC.md
                  - SPSC: Engine/Core/Concurrency/Channel/SPSC.md
          - Containers:
              - Overview: Engine/Core/Containers/index.md
              - Array:
                  - Overview: Engine/Core/Containers/Array/index.md
                  - Inline: Engine/Core/Containers/Array/Inline.md
                  - PMR: Engine/Core/Containers/Array/PMR.md
              - Cache:
                  - Overview: Engine/Core/Containers/Cache/index.md
                  - LRU: Engine/Core/Containers/Cache/LRU.md
              - List:
                  - Overview: Engine/Core/Containers/List/index.md
                  - Intrusive: Engine/Core/Containers/List/Intrusive.md
              - Map: Engine/Core/Containers/Map.md
              - Queue: Engine/Core/Containers/Queue.md
              - Set: Engine/Core/Containers/Set.md
              - SlotMap: Engine/Core/Containers/SlotMap.md
          - Delegate:
              - Overview: Engine/Core/Delegate/index.md
              - Multicast: Engine/Core/Delegate/Multicast.md
              - Unicast: Engine/Core/Delegate/Unicast.md
          - Font: Engine/Core/Font/index.md
          - Image:
              - Overview: Engine/Core/Image/index.md
              - Common: Engine/Core/Image/Common.md
              - Pixel: Engine/Core/Image/Pixel.md
          - Log:
              - Overview: Engine/Core/Log/index.md
              - Logger: Engine/Core/Log/Logger.md
          - Limits:
              - Overview: Engine/Core/Limits/index.md
              - Numeric: Engine/Core/Limits/Numeric.md
          - Indexing:
              - Overview: Engine/Core/Indexing/index.md
              - CuckooFilter: Engine/Core/Indexing/CuckooFilter.md
              - SpatialHash: Engine/Core/Indexing/SpatialHash.md
          - Math:
              - Overview: Engine/Core/Math/index.md
              - Algebra:
                  - Overview: Engine/Core/Math/Algebra/index.md
                  - Matrix: Engine/Core/Math/Algebra/Matrix.md
                  - Quaternion: Engine/Core/Math/Algebra/Quaternion.md
                  - Vector: Engine/Core/Math/Algebra/Vector.md
              - Arithmetic:
                  - Overview: Engine/Core/Math/Arithmetic/index.md
                  - Interval: Engine/Core/Math/Arithmetic/Interval.md
                  - Operation: Engine/Core/Math/Arithmetic/Operation.md
              - Bit: Engine/Core/Math/Bit.md
              - Color:
                  - Overview: Engine/Core/Math/Color/index.md
                  - Common: Engine/Core/Math/Color/Common.md
                  - Linear: Engine/Core/Math/Color/Linear.md
              - Constants: Engine/Core/Math/Constants.md
              - Geometry:
                  - Overview: Engine/Core/Math/Geometry/index.md
                  - Area: Engine/Core/Math/Geometry/Area.md
                  - Box: Engine/Core/Math/Geometry/Box.md
                  - Point: Engine/Core/Math/Geometry/Point.md
                  - Rotation: Engine/Core/Math/Geometry/Rotation.md
                  - Transform: Engine/Core/Math/Geometry/Transform.md
              - Hash:
                  - Overview: Engine/Core/Math/Hash/index.md
                  - CityHash: Engine/Core/Math/Hash/CityHash.md
                  - GoldenRatio: Engine/Core/Math/Hash/GoldenRatio.md
              - Interpolation: Engine/Core/Math/Interpolation.md
              - Kernel:
                  - Overview: Engine/Core/Math/Kernal/index.md
                  - Gaussian: Engine/Core/Math/Kernal/Gaussian.md
              - Random:
                  - Overview: Engine/Core/Math/Random/index.md
                  - RNG: Engine/Core/Math/Random/RNG.md
                  - PCG: Engine/Core/Math/Random/RNG/PCG.md
                  - Seed: Engine/Core/Math/Random/Seed.md
              - Trigonometry:
                  - Overview: Engine/Core/Math/Trigonometry/index.md
                  - Degree: Engine/Core/Math/Trigonometry/Degree.md
                  - Radian: Engine/Core/Math/Trigonometry/Radian.md
          - Meta:
              - Overview: Engine/Core/Meta/index.md
              - Cast: Engine/Core/Meta/Cast.md
          - OS:
              - Overview: Engine/Core/OS/index.md
              - FileSystem:
                  - Overview: Engine/Core/OS/FileSystem/index.md
                  - File: Engine/Core/OS/FileSystem/File.md
              - Memory:
                  - Overview: Engine/Core/OS/Memory/index.md
                  - Arena: Engine/Core/OS/Memory/Arena.md
              - Thread:
                  - Overview: Engine/Core/OS/Thread/index.md
                  - Queue:
                      - Overview: Engine/Core/OS/Thread/Queue/index.md
                      - MPSC: Engine/Core/OS/Thread/Queue/MPSC.md
                      - SPSC: Engine/Core/OS/Thread/Queue/SPSC.md
                  - Sync:
                      - Overview: Engine/Core/OS/Thread/Sync/index.md
                      - Atomic: Engine/Core/OS/Thread/Sync/Atomic.md
                      - CriticalSection: Engine/Core/OS/Thread/Sync/CriticalSection.md
                      - Event: Engine/Core/OS/Thread/Sync/Event.md
                      - RWLock: Engine/Core/OS/Thread/Sync/RWLock.md
                      - SpinLock: Engine/Core/OS/Thread/Sync/SpinLock.md
              - Time:
                  - Overview: Engine/Core/OS/Time/index.md
                  - Clock: Engine/Core/OS/Time/Clock.md
                  - Common: Engine/Core/OS/Time/Common.md
                  - Duration: Engine/Core/OS/Time/Duration.md
                  - TimePoint: Engine/Core/OS/Time/TimePoint.md
          - Traits:
              - Overview: Engine/Core/Traits/index.md
              - Flags: Engine/Core/Traits/Flags.md
          - Types:
              - Overview: Engine/Core/Types/index.md
              - Char: Engine/Core/Types/Char.md
              - Function: Engine/Core/Types/Function.md
              - Half: Engine/Core/Types/Half.md
              - Handle: Engine/Core/Types/Handle.md
              - JSON: Engine/Core/Types/JSON.md
              - Name:
                  - Overview: Engine/Core/Types/Name/index.md
                  - NamePool: Engine/Core/Types/Name/NamePool/NamePool.md
                  - Common: Engine/Core/Types/Name/NamePool/Common.md
                  - NameEntryTable: Engine/Core/Types/Name/NamePool/NameEntryTable.md
                  - NameTokenTable: Engine/Core/Types/Name/NamePool/NameTokenTable.md
              - Optional: Engine/Core/Types/Optional.md
              - Path: Engine/Core/Types/Path.md
              - Pointer:
                  - Overview: Engine/Core/Types/Pointer/index.md
                  - Shared: Engine/Core/Types/Pointer/Shared.md
                  - Unique: Engine/Core/Types/Pointer/Unique.md
                  - Weak: Engine/Core/Types/Pointer/Weak.md
              - String: Engine/Core/Types/String.md
              - Text: Engine/Core/Types/Text.md
              - Tuple: Engine/Core/Types/Tuple.md
              - UUID: Engine/Core/Types/UUID.md
      - Platform:
          - Overview: Engine/Platform/index.md
          - Interface:
              - Overview: Engine/Platform/Interface/index.md
              - Window: Engine/Platform/Interface/Window.md
              - Path: Engine/Platform/Interface/Path.md
              - FileSystem: Engine/Platform/Interface/FileSystem.md
              - Library: Engine/Platform/Interface/Library.md
          - GLFW:
              - Overview: Engine/Platform/GLFW/index.md
              - Device:
                  - Keyboard: Engine/Platform/GLFW/Device/Keyboard.md
                  - Mouse: Engine/Platform/GLFW/Device/Mouse.md
              - Window: Engine/Platform/GLFW/Window.md
          - Null:
              - Overview: Engine/Platform/Null/index.md
          - Windows:
              - Overview: Engine/Platform/Windows/index.md
              - Window: Engine/Platform/Windows/Window.md
              - Path: Engine/Platform/Windows/Path.md
              - FileSystem: Engine/Platform/Windows/FileSystem.md
              - Library: Engine/Platform/Windows/Library.md
          - MacOS:
              - Overview: Engine/Platform/MacOS/index.md
              - Window: Engine/Platform/MacOS/Window.md
              - Path: Engine/Platform/MacOS/Path.md
              - FileSystem: Engine/Platform/MacOS/FileSystem.md
              - Library: Engine/Platform/MacOS/Library.md
      - Runtime:
          - Overview: Engine/Runtime/index.md
          - AssetHub:
              - Overview: Engine/Runtime/AssetHub/index.md
              - Asset: Engine/Runtime/AssetHub/Asset.md
              - Image:
                  - Overview: Engine/Runtime/AssetHub/Image/index.md
                  - Common: Engine/Runtime/AssetHub/Image/Common.md
                  - PNG: Engine/Runtime/AssetHub/Image/PNG.md
                  - EXR: Engine/Runtime/AssetHub/Image/EXR.md
                  - Wrapper: Engine/Runtime/AssetHub/Image/Wrapper.md
              - Font:
                  - Overview: Engine/Runtime/AssetHub/Font/index.md
                  - FreeType: Engine/Runtime/AssetHub/Font/FreeType.md
              - Shader: Engine/Runtime/AssetHub/Shader.md
          - Audio:
              - Overview: Engine/Runtime/Audio/index.md
              - Interface: Engine/Runtime/Audio/Interface.md
              - Null: Engine/Runtime/Audio/Null.md
              - Wwise: Engine/Runtime/Audio/Wwise.md
              - Wwise-IO: Engine/Runtime/Audio/Wwise-IO.md
          - Global:
              - Overview: Engine/Runtime/Global/index.md
              - Configuration: Engine/Runtime/Global/Configuration.md
              - Service: Engine/Runtime/Global/Service.md
          - Graphics:
              - Overview: Engine/Runtime/Graphics/index.md
              - Framework: Engine/Runtime/Graphics/Framework.md
              - Material: Engine/Runtime/Graphics/Material.md
              - PipelineCache: Engine/Runtime/Graphics/PipelineCache.md
              - RenderGraph: Engine/Runtime/Graphics/RenderGraph.md
              - Scene:
                  - Overview: Engine/Runtime/Graphics/Scene/index.md
                  - Camera: Engine/Runtime/Graphics/Scene/Camera.md
                  - Light: Engine/Runtime/Graphics/Scene/Light.md
                  - Renderable: Engine/Runtime/Graphics/Scene/Renderable.md
          - Input:
              - Overview: Engine/Runtime/Input/index.md
              - Action: Engine/Runtime/Input/Action.md
              - Device:
                  - Overview: Engine/Runtime/Input/Device/index.md
                  - Keyboard: Engine/Runtime/Input/Device/Keyboard.md
                  - Mouse: Engine/Runtime/Input/Device/Mouse.md
              - Mapping: Engine/Runtime/Input/Mapping.md
          - Physics2D:
              - Overview: Engine/Runtime/Physics2D/index.md
              - Common: Engine/Runtime/Physics2D/Common.md
              - RigidBody: Engine/Runtime/Physics2D/RigidBody.md
          - RHI:
              - Overview: Engine/Runtime/RHI/index.md
              - Barrier: Engine/Runtime/RHI/Barrier.md
              - CommandList: Engine/Runtime/RHI/CommandList.md
              - Common: Engine/Runtime/RHI/Common.md
              - Registry:
                  - Overview: Engine/Runtime/RHI/Registry/index.md
                  - Handle: Engine/Runtime/RHI/Registry/Handle.md
                  - Item: Engine/Runtime/RHI/Registry/Item.md
              - Resource:
                  - Overview: Engine/Runtime/RHI/Resource/index.md
                  - Buffer: Engine/Runtime/RHI/Resource/Buffer.md
                  - Texture: Engine/Runtime/RHI/Resource/Texture.md
                  - Sampler: Engine/Runtime/RHI/Resource/Sampler.md
                  - DescriptorSet: Engine/Runtime/RHI/Resource/DescriptorSet.md
                  - Shader: Engine/Runtime/RHI/Resource/Shader.md
                  - RenderPass: Engine/Runtime/RHI/Resource/RenderPass.md
                  - ComputePass: Engine/Runtime/RHI/Resource/ComputePass.md
              - StagingRing: Engine/Runtime/RHI/StagingRing.md
              - SwapChain: Engine/Runtime/RHI/SwapChain.md
              - Vulkan:
                  - Overview: Engine/Runtime/RHI/Vulkan/index.md
                  - Allocator: Engine/Runtime/RHI/Vulkan/Allocator.md
                  - Attachment:
                      - Overview: Engine/Runtime/RHI/Vulkan/Attachment/index.md
                      - Color: Engine/Runtime/RHI/Vulkan/Attachment/Color.md
                      - DepthStencil: Engine/Runtime/RHI/Vulkan/Attachment/DepthStencil.md
                  - Buffer: Engine/Runtime/RHI/Vulkan/Buffer.md
                  - CommandBuffer: Engine/Runtime/RHI/Vulkan/CommandBuffer.md
                  - CommandPool: Engine/Runtime/RHI/Vulkan/CommandPool.md
                  - Common: Engine/Runtime/RHI/Vulkan/Common.md
                  - DescriptorPool: Engine/Runtime/RHI/Vulkan/DescriptorPool.md
                  - DescriptorSet: Engine/Runtime/RHI/Vulkan/DescriptorSet.md
                  - DescriptorSetLayout: Engine/Runtime/RHI/Vulkan/DescriptorSetLayout.md
                  - Image: Engine/Runtime/RHI/Vulkan/Image.md
                  - Loader: Engine/Runtime/RHI/Vulkan/Loader.md
                  - Pipeline:
                      - Overview: Engine/Runtime/RHI/Vulkan/Pipeline/index.md
                      - Cache: Engine/Runtime/RHI/Vulkan/Pipeline/Cache.md
                      - Layout: Engine/Runtime/RHI/Vulkan/Pipeline/Layout.md
                      - Compute: Engine/Runtime/RHI/Vulkan/Pipeline/Compute.md
                      - Render: Engine/Runtime/RHI/Vulkan/Pipeline/Render.md
                  - Sampler: Engine/Runtime/RHI/Vulkan/Sampler.md
                  - ShaderModule: Engine/Runtime/RHI/Vulkan/ShaderModule.md
                  - Sync:
                      - Overview: Engine/Runtime/RHI/Vulkan/Sync/index.md
                      - Fence: Engine/Runtime/RHI/Vulkan/Sync/Fence.md
                      - Semaphore: Engine/Runtime/RHI/Vulkan/Sync/Semaphore.md
          - Tasks:
              - Overview: Engine/Runtime/Tasks/index.md
              - Interface: Engine/Runtime/Tasks/Interface.md
              - Scheduler: Engine/Runtime/Tasks/Scheduler.md
          - UI:
              - Overview: Engine/Runtime/UI/index.md
              - Context: Engine/Runtime/UI/Context.md
              - ImGUI: Engine/Runtime/UI/ImGUI.md
          - Window: Engine/Runtime/Window/index.md

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search

extra_css:
  - assets/styles/visera.css
