module;
#include <Visera-Platform.hpp>
#include <GLFW/glfw3.h>
#include <array>
export module Visera.Platform.Cross.GLFW.Keyboard;
#define VISERA_MODULE_NAME "Platform.Cross"

export namespace Visera
{
    /** Keyboard modifier flags (maps to GLFW_MOD_*). Use operator| to combine. */
    enum class EKeyboardModifier : UInt8
    {
        None     = 0,
        Shift    = GLFW_MOD_SHIFT,
        Control  = GLFW_MOD_CONTROL,
        Alt      = GLFW_MOD_ALT,
        Super    = GLFW_MOD_SUPER,
        CapsLock = GLFW_MOD_CAPS_LOCK,
        NumLock  = GLFW_MOD_NUM_LOCK,
    };

    constexpr EKeyboardModifier operator|(EKeyboardModifier I_A, EKeyboardModifier I_B)
    { return static_cast<EKeyboardModifier>(static_cast<UInt8>(I_A) | static_cast<UInt8>(I_B)); }
    constexpr EKeyboardModifier operator&(EKeyboardModifier I_A, EKeyboardModifier I_B)
    { return static_cast<EKeyboardModifier>(static_cast<UInt8>(I_A) & static_cast<UInt8>(I_B)); }

    enum class EGLFWKeyboardAction : UInt8
    {
        Release = GLFW_RELEASE,
        Press   = GLFW_PRESS,
    };

    enum class EGLFWKeyboardKey : Int32
    {
        Unknown = GLFW_KEY_UNKNOWN,
        Space = GLFW_KEY_SPACE,
        Apostrophe = GLFW_KEY_APOSTROPHE,
        Comma = GLFW_KEY_COMMA,
        Minus = GLFW_KEY_MINUS,
        Period = GLFW_KEY_PERIOD,
        Slash = GLFW_KEY_SLASH,
        Num0 = GLFW_KEY_0,
        Num1 = GLFW_KEY_1,
        Num2 = GLFW_KEY_2,
        Num3 = GLFW_KEY_3,
        Num4 = GLFW_KEY_4,
        Num5 = GLFW_KEY_5,
        Num6 = GLFW_KEY_6,
        Num7 = GLFW_KEY_7,
        Num8 = GLFW_KEY_8,
        Num9 = GLFW_KEY_9,
        Semicolon = GLFW_KEY_SEMICOLON,
        Equal = GLFW_KEY_EQUAL,
        A = GLFW_KEY_A,
        B = GLFW_KEY_B,
        C = GLFW_KEY_C,
        D = GLFW_KEY_D,
        E = GLFW_KEY_E,
        F = GLFW_KEY_F,
        G = GLFW_KEY_G,
        H = GLFW_KEY_H,
        I = GLFW_KEY_I,
        J = GLFW_KEY_J,
        K = GLFW_KEY_K,
        L = GLFW_KEY_L,
        M = GLFW_KEY_M,
        N = GLFW_KEY_N,
        O = GLFW_KEY_O,
        P = GLFW_KEY_P,
        Q = GLFW_KEY_Q,
        R = GLFW_KEY_R,
        S = GLFW_KEY_S,
        T = GLFW_KEY_T,
        U = GLFW_KEY_U,
        V = GLFW_KEY_V,
        W = GLFW_KEY_W,
        X = GLFW_KEY_X,
        Y = GLFW_KEY_Y,
        Z = GLFW_KEY_Z,
        LeftBracket = GLFW_KEY_LEFT_BRACKET,
        Backslash = GLFW_KEY_BACKSLASH,
        RightBracket = GLFW_KEY_RIGHT_BRACKET,
        GraveAccent = GLFW_KEY_GRAVE_ACCENT,
        World1 = GLFW_KEY_WORLD_1,
        World2 = GLFW_KEY_WORLD_2,
        Escape = GLFW_KEY_ESCAPE,
        Enter = GLFW_KEY_ENTER,
        Tab = GLFW_KEY_TAB,
        Backspace = GLFW_KEY_BACKSPACE,
        Insert = GLFW_KEY_INSERT,
        Delete = GLFW_KEY_DELETE,
        Right = GLFW_KEY_RIGHT,
        Left = GLFW_KEY_LEFT,
        Down = GLFW_KEY_DOWN,
        Up = GLFW_KEY_UP,
        PageUp = GLFW_KEY_PAGE_UP,
        PageDown = GLFW_KEY_PAGE_DOWN,
        Home = GLFW_KEY_HOME,
        End = GLFW_KEY_END,
        CapsLock = GLFW_KEY_CAPS_LOCK,
        ScrollLock = GLFW_KEY_SCROLL_LOCK,
        NumLock = GLFW_KEY_NUM_LOCK,
        PrintScreen = GLFW_KEY_PRINT_SCREEN,
        Pause = GLFW_KEY_PAUSE,
        F1 = GLFW_KEY_F1,
        F2 = GLFW_KEY_F2,
        F3 = GLFW_KEY_F3,
        F4 = GLFW_KEY_F4,
        F5 = GLFW_KEY_F5,
        F6 = GLFW_KEY_F6,
        F7 = GLFW_KEY_F7,
        F8 = GLFW_KEY_F8,
        F9 = GLFW_KEY_F9,
        F10 = GLFW_KEY_F10,
        F11 = GLFW_KEY_F11,
        F12 = GLFW_KEY_F12,
        F13 = GLFW_KEY_F13,
        F14 = GLFW_KEY_F14,
        F15 = GLFW_KEY_F15,
        F16 = GLFW_KEY_F16,
        F17 = GLFW_KEY_F17,
        F18 = GLFW_KEY_F18,
        F19 = GLFW_KEY_F19,
        F20 = GLFW_KEY_F20,
        F21 = GLFW_KEY_F21,
        F22 = GLFW_KEY_F22,
        F23 = GLFW_KEY_F23,
        F24 = GLFW_KEY_F24,
        F25 = GLFW_KEY_F25,
        KP0 = GLFW_KEY_KP_0,
        KP1 = GLFW_KEY_KP_1,
        KP2 = GLFW_KEY_KP_2,
        KP3 = GLFW_KEY_KP_3,
        KP4 = GLFW_KEY_KP_4,
        KP5 = GLFW_KEY_KP_5,
        KP6 = GLFW_KEY_KP_6,
        KP7 = GLFW_KEY_KP_7,
        KP8 = GLFW_KEY_KP_8,
        KP9 = GLFW_KEY_KP_9,
        KPDecimal = GLFW_KEY_KP_DECIMAL,
        KPDivide = GLFW_KEY_KP_DIVIDE,
        KPMultiply = GLFW_KEY_KP_MULTIPLY,
        KPSubtract = GLFW_KEY_KP_SUBTRACT,
        KPAdd = GLFW_KEY_KP_ADD,
        KPEnter = GLFW_KEY_KP_ENTER,
        KPEqual = GLFW_KEY_KP_EQUAL,
        LeftShift = GLFW_KEY_LEFT_SHIFT,
        LeftControl = GLFW_KEY_LEFT_CONTROL,
        LeftAlt = GLFW_KEY_LEFT_ALT,
        LeftSuper = GLFW_KEY_LEFT_SUPER,
        RightShift = GLFW_KEY_RIGHT_SHIFT,
        RightControl = GLFW_KEY_RIGHT_CONTROL,
        RightAlt = GLFW_KEY_RIGHT_ALT,
        RightSuper = GLFW_KEY_RIGHT_SUPER,
        Menu = GLFW_KEY_MENU,
    };

    inline constexpr EGLFWKeyboardKey GLFWKeyboardKeys[]{
        EGLFWKeyboardKey::Space, EGLFWKeyboardKey::Apostrophe, EGLFWKeyboardKey::Comma,
        EGLFWKeyboardKey::Minus, EGLFWKeyboardKey::Period, EGLFWKeyboardKey::Slash,
        EGLFWKeyboardKey::Num0, EGLFWKeyboardKey::Num1, EGLFWKeyboardKey::Num2,
        EGLFWKeyboardKey::Num3, EGLFWKeyboardKey::Num4, EGLFWKeyboardKey::Num5,
        EGLFWKeyboardKey::Num6, EGLFWKeyboardKey::Num7, EGLFWKeyboardKey::Num8,
        EGLFWKeyboardKey::Num9, EGLFWKeyboardKey::Semicolon, EGLFWKeyboardKey::Equal,
        EGLFWKeyboardKey::A, EGLFWKeyboardKey::B, EGLFWKeyboardKey::C,
        EGLFWKeyboardKey::D, EGLFWKeyboardKey::E, EGLFWKeyboardKey::F,
        EGLFWKeyboardKey::G, EGLFWKeyboardKey::H, EGLFWKeyboardKey::I,
        EGLFWKeyboardKey::J, EGLFWKeyboardKey::K, EGLFWKeyboardKey::L,
        EGLFWKeyboardKey::M, EGLFWKeyboardKey::N, EGLFWKeyboardKey::O,
        EGLFWKeyboardKey::P, EGLFWKeyboardKey::Q, EGLFWKeyboardKey::R,
        EGLFWKeyboardKey::S, EGLFWKeyboardKey::T, EGLFWKeyboardKey::U,
        EGLFWKeyboardKey::V, EGLFWKeyboardKey::W, EGLFWKeyboardKey::X,
        EGLFWKeyboardKey::Y, EGLFWKeyboardKey::Z,
        EGLFWKeyboardKey::LeftBracket, EGLFWKeyboardKey::Backslash,
        EGLFWKeyboardKey::RightBracket, EGLFWKeyboardKey::GraveAccent,
        EGLFWKeyboardKey::World1, EGLFWKeyboardKey::World2,
        EGLFWKeyboardKey::Escape, EGLFWKeyboardKey::Enter, EGLFWKeyboardKey::Tab,
        EGLFWKeyboardKey::Backspace, EGLFWKeyboardKey::Insert, EGLFWKeyboardKey::Delete,
        EGLFWKeyboardKey::Right, EGLFWKeyboardKey::Left, EGLFWKeyboardKey::Down,
        EGLFWKeyboardKey::Up, EGLFWKeyboardKey::PageUp, EGLFWKeyboardKey::PageDown,
        EGLFWKeyboardKey::Home, EGLFWKeyboardKey::End,
        EGLFWKeyboardKey::CapsLock, EGLFWKeyboardKey::ScrollLock, EGLFWKeyboardKey::NumLock,
        EGLFWKeyboardKey::PrintScreen, EGLFWKeyboardKey::Pause,
        EGLFWKeyboardKey::F1, EGLFWKeyboardKey::F2, EGLFWKeyboardKey::F3,
        EGLFWKeyboardKey::F4, EGLFWKeyboardKey::F5, EGLFWKeyboardKey::F6,
        EGLFWKeyboardKey::F7, EGLFWKeyboardKey::F8, EGLFWKeyboardKey::F9,
        EGLFWKeyboardKey::F10, EGLFWKeyboardKey::F11, EGLFWKeyboardKey::F12,
        EGLFWKeyboardKey::F13, EGLFWKeyboardKey::F14, EGLFWKeyboardKey::F15,
        EGLFWKeyboardKey::F16, EGLFWKeyboardKey::F17, EGLFWKeyboardKey::F18,
        EGLFWKeyboardKey::F19, EGLFWKeyboardKey::F20, EGLFWKeyboardKey::F21,
        EGLFWKeyboardKey::F22, EGLFWKeyboardKey::F23, EGLFWKeyboardKey::F24,
        EGLFWKeyboardKey::F25,
        EGLFWKeyboardKey::KP0, EGLFWKeyboardKey::KP1, EGLFWKeyboardKey::KP2,
        EGLFWKeyboardKey::KP3, EGLFWKeyboardKey::KP4, EGLFWKeyboardKey::KP5,
        EGLFWKeyboardKey::KP6, EGLFWKeyboardKey::KP7, EGLFWKeyboardKey::KP8,
        EGLFWKeyboardKey::KP9,
        EGLFWKeyboardKey::KPDecimal, EGLFWKeyboardKey::KPDivide,
        EGLFWKeyboardKey::KPMultiply, EGLFWKeyboardKey::KPSubtract,
        EGLFWKeyboardKey::KPAdd, EGLFWKeyboardKey::KPEnter, EGLFWKeyboardKey::KPEqual,
        EGLFWKeyboardKey::LeftShift, EGLFWKeyboardKey::LeftControl,
        EGLFWKeyboardKey::LeftAlt, EGLFWKeyboardKey::LeftSuper,
        EGLFWKeyboardKey::RightShift, EGLFWKeyboardKey::RightControl,
        EGLFWKeyboardKey::RightAlt, EGLFWKeyboardKey::RightSuper,
        EGLFWKeyboardKey::Menu,
    };

    inline constexpr Int32 GLFWKeyboardKeyLast = GLFW_KEY_MENU;
}
