if(NOT VISERA_RUNTIME_EXTERNAL_DIR)
    message(FATAL_ERROR "please include 'install.cmake' before installing any package.")
endif()

macro(link_vulkan in_target)
    message(STATUS "\nLinking Vulkan (Vulkan::Vulkan)")

    if(NOT TARGET Vulkan::Vulkan)
        set(VULKAN_REQUIRED_MINIMAL_VERSION "1.4.0")

        if(NOT DEFINED ENV{VULKAN_SDK})
            message(FATAL_ERROR "Failed to find VulkanSDK on your system!")
        else()
            # Extract the version from the path
            string(REGEX MATCH "[0-9]+\\.[0-9]+\\.[0-9]+" VULKAN_VERSION "$ENV{VULKAN_SDK}")
            message(STATUS "Found VulkanSDK ${VULKAN_VERSION} on current system.")
            if(VULKAN_VERSION)
                # Compare with required version (1.4.0)
                if(VULKAN_VERSION VERSION_LESS ${VULKAN_REQUIRED_MINIMAL_VERSION})
                    message(FATAL_ERROR "VulkanSDK version is required >= 1.4.0, while current version is ${VULKAN_VERSION}")
                endif()
            else()
                message(WARNING "Could not determine Vulkan SDK version.")
            endif()
        endif()
    endif()

    find_package(Vulkan REQUIRED)
    target_link_libraries(${in_target} PUBLIC Vulkan::Vulkan)
endmacro()